<?xml version="1.0"?>
<package format="3">
  <name>homo_multirobot_mocap_tools</name>
  <version>0.1.0</version>
  <description>VRPN motion-capture test utilities for the multi-robot workspace.</description>
  <maintainer email="l1anggmgo@example.com">l1anggmgo</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
