controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omnidirectional_controller:
      type: omnidirectional_controllers/OmnidirectionalController

omnidirectional_controller:
  ros__parameters:
    wheel_names:
      - robot2_front_wheel_joint
      - robot2_left_wheel_joint
      - robot2_right_wheel_joint

    robot_radius: 0.24
    wheel_radius: 0.03
    gamma: 60.0

    odom_frame_id: robot2_odom
    base_frame_id: robot2_base_footprint
    open_loop: false
    enable_odom_tf: false
    odom_numeric_integration_method: euler_forward
    publish_rate: 50.0

    use_stamped_vel: false
    cmd_vel_timeout: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.01]

